import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "harpreet",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "T-shirt 1",
      category: "Shirts",
      image: "/images/image1.jpg",
      price: 300,
      countInStock: 10,
      brand: "Pizza",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "T-shirt 2",
      category: "Shirts",
      image: "/images/image2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "T-shirt 3",
      category: "Shirts",
      image: "/images/image3.jpg",
      price: 80,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "T-shirt 4",
      category: "Pants",
      image: "/images/image4.jpg",
      price: 100,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "T-shirt 5",
      category: "Pants",
      image: "/images/image5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "T-shirt 6",
      category: "Pants",
      image: "/images/image6.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "T-shirt 7",
      category: "Pants",
      image: "/images/image7.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "T-shirt 8",
      category: "Pants",
      image: "/images/image8.jpg",
      price: 85,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "T-shirt 9",
      category: "Pants",
      image: "/images/image9.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
